name: Deploy Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    uses: viniciusmorao-dev/pipeline-devops/.github/workflows/pipeline.yaml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USER: ${{ secrets.VM_USER }}
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}