name: Deploy Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    uses: viniciusmorao-dev/pipeline-devops/.github/workflows/pipeline.yaml@main
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}